version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/python
  python: circleci/python@0.3.2

jobs:
  backend-test:
    docker:
      - image: circleci/python:3.7.2-stretch-browsers
      - image: circleci/postgres:9.6.7
        environment:
          POSTGRES_USER: know_your_planet_team
          POSTGRES_DB: know_your_planet

    resource_class: small

    executor: python/default

    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: | 
            python -m flake8
            python manage.py test

workflows:
  main:
    jobs:
      - backend-test
